"""added more  positive comments

Revision ID: 19c8f3e1c0a0
Revises: dfe317e42234
Create Date: 2024-01-22 22:14:10.386564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c8f3e1c0a0'
down_revision = 'dfe317e42234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolios')
    op.drop_table('engagements')
    op.drop_table('chefs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chefs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('specialty', sa.VARCHAR(), nullable=True),
    sa.Column('bio', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('comment_body', sa.TEXT(), nullable=True),
    sa.Column('likes', sa.INTEGER(), nullable=True),
    sa.Column('chef_id', sa.INTEGER(), nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['chef_id'], ['chefs.id'], name='fk_engagements_chef_id_chefs'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name='fk_engagements_portfolio_id_portfolios'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
