"""added elements

Revision ID: 3a34bc62e382
Revises: 19c8f3e1c0a0
Create Date: 2024-01-23 12:53:01.104889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a34bc62e382'
down_revision = '19c8f3e1c0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chefs', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
