"""adjustments

Revision ID: 490358c36506
Revises: acabd3d05e5d
Create Date: 2024-01-23 13:35:55.726329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490358c36506'
down_revision = 'acabd3d05e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_portfolios')
    with op.batch_alter_table('chefs', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.VARCHAR(), nullable=True))

    op.create_table('_alembic_tmp_portfolios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('chef_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['chef_id'], ['chefs.id'], name='fk_portfolios_chef_id_chefs'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
