"""added many-to-many

Revision ID: acabd3d05e5d
Revises: 3a34bc62e382
Create Date: 2024-01-23 13:14:26.008058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acabd3d05e5d'
down_revision = '3a34bc62e382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chef_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_portfolios_chef_id_chefs'), 'chefs', ['chef_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_portfolios_chef_id_chefs'), type_='foreignkey')
        batch_op.drop_column('chef_id')

    # ### end Alembic commands ###
