"""Add likes column to portfolios

Revision ID: d3e15b8a869e
Revises: e610d8d32e53
Create Date: 2024-01-24 14:45:26.905008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e15b8a869e'
down_revision = 'e610d8d32e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
