"""adjustments

Revision ID: e610d8d32e53
Revises: 490358c36506
Create Date: 2024-01-23 13:48:32.924053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e610d8d32e53'
down_revision = '490358c36506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chef_portfolio_association',
    sa.Column('chef_id', sa.Integer(), nullable=True),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chef_id'], ['chefs.id'], name=op.f('fk_chef_portfolio_association_chef_id_chefs')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_chef_portfolio_association_portfolio_id_portfolios'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chef_portfolio_association')
    # ### end Alembic commands ###
